### ISSUE TITLE
一个崩溃

### ISSUE THREAD

**Issue by kingsNow** [jkpang/PPGetAddressBook#2]
iOS9系统下，在设置-隐私-通讯录-更改当前应用权限后crash。并且crash后，重复卸载安装app 不再弹出授权提醒。

**Comment by jkpang** [comment]
@kingsNow 
1. 你是在Debug(调试)的情况下更改当前应用权限的吧,这种情况下崩溃是正常现象.,不连着Xcode调试就不会出现此情况
2在卸载APP后重新安装不再弹出提示框是因为系统已经记住用户对此APP已经做过联系人授权操作了,所以就不会再弹出来(你可以换一个开发者账号测试就会弹出)

**Comment by kingsNow** [comment]
@jkpang 
感谢你的回答！意思是release下，不连着xcode就没关系了，对吧。为什么会crash呢？可否告知原因。

**Comment by jkpang** [comment]
这个原因我也不是太清楚，明天我去问问度娘看看

AndyPang

**Comment by kingsNow** [comment]
@jkpang Thank you! 都会出现这个问题。可能是系统造成的。

**Comment by jkpang** [comment]
@kingsNow 刚刚问了度娘,连着Xcode调试时更改系统权限会崩溃的原因: http://www.jianshu.com/p/ada52c520ccb  ,希望能帮到你!
