### ISSUE TITLE
在iOS8系统上,由于联系人数据较多的时候,会卡很久

### ISSUE THREAD

**Issue by LGLee** [jkpang/PPGetAddressBook#3]
我当前项目使用的是PPGetAddressBook获取联系人,但是在在iOS8系统上,由于联系人数据较多的时候,会卡很久.没有提示,也不能做任何操作.

**Comment by jkpang** [comment]
你是用的哪个版本？我把联系人获取，排序等操作放在了子线程，不会阻塞主线程的操作，而且获取速度我已经优化的很快了，应该不会出现这种情况

AndyPang

**Comment by LGLee** [comment]
目前使用的是最新的版本，暂未发现问题，感谢你智慧的贡献
