### ISSUE TITLE
排序会有问题 ~ 试试 沈彩 会排列到 c 那边去

### ISSUE THREAD

**Issue by angBiu** [jkpang/PPGetAddressBook#4]

**Comment by jkpang** [comment]
刚刚试了一下,确实会这样,我是使用系统API转换的拼音,可能是没有转换准确. "沈"是一个多音字 ,可能是系统首先识别为chen
![示例图](https://cloud.githubusercontent.com/assets/17583451/19720072/31dde2ea-9b9f-11e6-9c2d-0e3919abe8fb.png)
这个问题我会在之后的版本解决的@angBiu

**Comment by angBiu** [comment]
恩恩。。。刚刚看到了。。+_+ 谢谢

**Comment by jkpang** [comment]
这个问题解决了我会在第一时间通知你 @angBiu

**Comment by jkpang** [comment]
多音字问题已解决,版本已经更新至 0.2.7 ,欢迎使用! @angBiu
